_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    # we provide implementation of normalization option in improvements part.
    NORMALIZE_REG_TARGETS: True  # fix with True
   
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
  #MAX_ITER: 300 #500
  IMS_PER_BATCH: 1 # 1 GPU - can be 4 - https://github.com/intelpro/PA1/blob/master/run.sh
  #BASE_LR: 0.001
  #CHECKPOINT_PERIOD: 300 # https://medium.com/towards-artificial-intelligence/number-plate-detection-recognition-detectron-v2-5ddad2a532d0
DATASETS:
  TRAIN: ("custom_dataset_train","custom_dataset_val")
  TEST: ("custom_dataset_test",)
DATALOADER:
    NUM_WORKERS: 1
OUTPUT_DIR: "output/fcos/R_50_1x"
